
language: python
python:
  - "3.8"

before_install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list  | sudo tee -a /etc/apt/sources.list.d/mssql-release.list
  - sudo apt-get update
  - sudo ACCEPT_EULA=Y apt-get -y install msodbcsql17
  - sudo ACCEPT_EULA=Y apt-get -y install mssql-tools

install:
  - echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
  - echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
  - source ~/.bashrc
  - sudo apt-get -y install unixodbc-dev
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover -s tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # safelist
branches:
  only:
  - master