language: python
python:
- '3.8'
before_install:
- curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
- sudo curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list  | sudo tee
  -a /etc/apt/sources.list.d/mssql-release.list
- sudo apt-get update
- sudo ACCEPT_EULA=Y apt-get -y install msodbcsql17
- sudo ACCEPT_EULA=Y apt-get -y install mssql-tools
install:
- echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
- echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
- source ~/.bashrc
- sudo apt-get -y install unixodbc-dev
- pip install -r requirements.txt
script:
- coverage run -m unittest discover -s tests
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: etrintel
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: VViT7KSXxX828wvNNr/akk5zoujKPqBWIPpLs6QXN4r5N8haFks4hGW1lyl3mHMy4tmmu5VboSoqH9lr34BudVA/WkMCFHIJI0rJhu4ySz3t98PUcBHnmI3z2IeYGotw7CVt0ORGdpJcH8DbFWfD4Ht1JHw1mzEe/mNhn1JSYUTpyLu92iMfi/ZGo7FaWRqY4oWmK37qtfKpWVRDeKZXNTVCeH5nVdVaEkpVZsbxy8WDm6aXGDHaF7AdgRyYlTX1Vy61Qyv4SjyIjF8nGEXJtqwMe3tT7hvHxrL0UKEYkdtYzLG+uDlX9Aedx70b2g+V6XRg5P+WacV+4Wswj1igBGZerpx179c2/V60ohaSjBXRsS3/cdBcAGJ3Q/ns8tERMa9/wD+lfd0cRRK7i2kDmrhGELhRPQbxEZGt7XfSE9ZUpOmNOz6uyUeE8LkVhgTeHVSjdAU2z/x+N4QJ4rDYyqBYos//c0rrMjwhK1ixCPHg03uVs2w8xfpJwOnCAMbPWNQqGmg04vPSbGQ3kVM/dYAy1c4Y66xT8aBBPt0xRwQEwV/2k0Mjlp8ObAufwJrumQYK+iU4fMypxhVIQfMNIOZR4A897TnRGrxxAXrg1ag0YfLSnENQMZUfWuuBVknBmnNBG9McoW0S5oOK/Ej4cwJ+chzeGjah0pN6mFik4wM=
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
